const colors = {
  light: {
    text: "#0F172A",
    tint: "#6D4AFF",
    background: "#F8FAFC",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#6D4AFF",
    primaryForeground: "#FFFFFF",
    secondary: "#F1F5F9",
    secondaryForeground: "#0F172A",
    muted: "#E2E8F0",
    mutedForeground: "#64748B",
    accent: "#00D4A4",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#F1F5F9",
    chatBubbleSent: "#6D4AFF",
    chatBubbleSentText: "#FFFFFF",
    chatBubbleReceived: "#FFFFFF",
    chatBubbleReceivedText: "#0F172A",
    online: "#00D4A4",
    unreadBadge: "#6D4AFF",
    headerBg: "#FFFFFF",
    tabBarBg: "#FFFFFF",
    missedCall: "#EF4444",
  },
  dark: {
    text: "#F8FAFC",
    tint: "#9B7FFF",
    background: "#0A0A0A",
    foreground: "#F8FAFC",
    card: "#111827",
    cardForeground: "#F8FAFC",
    primary: "#9B7FFF",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E2E",
    secondaryForeground: "#F8FAFC",
    muted: "#2D2D42",
    mutedForeground: "#94A3B8",
    accent: "#00D4A4",
    accentForeground: "#0A0A0A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D2D42",
    input: "#1E1E2E",
    chatBubbleSent: "#6D4AFF",
    chatBubbleSentText: "#FFFFFF",
    chatBubbleReceived: "#1E1E2E",
    chatBubbleReceivedText: "#F8FAFC",
    online: "#00D4A4",
    unreadBadge: "#6D4AFF",
    headerBg: "#0A0A0A",
    tabBarBg: "#0A0A0A",
    missedCall: "#EF4444",
  },
  radius: 16,
};

export default colors;
